package de.typology.parser;

public enum ReutersToken {
	STRING, UPPERCASE, OTHER, WS, LINESEPARATOR, EOF,
	//
	FULLSTOP, COMMA, SEMICOLON, COLON, HYPHEN, EXCLAMATIONMARK, QUESTIONMARK, QUOTATIONMARK, AND,

	//
	BRACES, CLOSEDBRACES,
	//
	P, CLOSEDP,
	//
	TITLE, CLOSEDTITLE,
	//
	TEXT, CLOSEDTEXT,
}
