#!/usr/bin/env python3
# encoding=UTF-8

import numpy
import matplotlib.pyplot as plt
import matplotlib.cbook as cbook
from sys import argv, exit

if len(argv) < 3:
    print(argv[0] + " <file> <num-bins>")
    exit()


def remove_outliers(values, percent):
    num_outliers = int(len(values) * percent / 100)
    print("Removing " + str(percent) + "% of outliers, in total removing " + str(num_outliers) + " outliers.")
    values.sort()
    bound = int(num_outliers/2)
    #return values[:-bound]
    return values[bound:-bound]


with open(argv[1]) as f:
    contents = f.read();
    values = list(map(float, contents.split()))

    if len(argv) >= 4:
        per_outliers = float(argv[3])
        if len(argv) == 4:
            values = remove_outliers(values, per_outliers)

    stats = cbook.boxplot_stats(values)[0]

    mean = stats['mean']
    std = numpy.std(values)

    median = stats['med']
    q1 = stats['q1']
    q3 = stats['q3']
    whislo = stats['whislo']
    whishi = stats['whishi']

    if len(argv) > 4:
        values = remove_outliers(values, per_outliers)

    print("mean:", mean)
    print("standard deviation:", std)
    print()
    print("lower whisker:", whislo)
    print("lower quartile:", q1)
    print("median:", median)
    print("upper quartile:", q3)
    print("upper whisker:", whishi)

    print(plt.hist(values, bins=int(argv[2]), color='y')[0])
    plt.axvline(mean,   linestyle='--', color='r', linewidth=2)
    plt.axvline(mean+std,   linestyle='-.', color='r', linewidth=2)
    plt.axvline(mean-std,   linestyle='-.', color='r', linewidth=2)

    plt.axvline(median, linestyle='-',  color='b', linewidth=2)
    plt.axvline(q1, linestyle='-.',  color='b', linewidth=2)
    plt.axvline(q3, linestyle='-.',  color='b', linewidth=2)
    plt.axvline(whislo, linestyle=':',  color='b', linewidth=2)
    plt.axvline(whishi, linestyle=':',  color='b', linewidth=2)
    plt.show()
