package de.typology.lexerParser;

public enum DGTTMToken {
	STRING, UPPERCASE, OTHER, WS, LINESEPARATOR, EOF,
	//
	FULLSTOP, COMMA, HYPHEN, EXCLAMATIONMARK, QUESTIONMARK, QUOTATIONMARK, AND,
	//
	BRACES, CLOSEDBRACES,
	//
	TUV, CLOSEDTUV,
	//
	SEG, CLOSEDSEG,
	//
	BODY, CLOSEDBODY,
}
