package de.typology.lexerParser;

public enum EnronToken {
	STRING, UPPERCASE, OTHER, WS, LINESEPARATOR, EOF, HEADER,
	//
	FULLSTOP, COMMA, SEMICOLON, HYPHEN, VERTICALBAR, SLASH, COLON, EQUALITYSIGN, ASTERISK, EXCLAMATIONMARK, QUESTIONMARK, QUOTATIONMARK, AND, AT,
	//
	MESSAGEID, DATE, FROM, TO, CC, BCC, SUBJECT, MIMEVERSION, CONTENTTYPE, CONTENTTRANSFERENCODING, XFROM, XTO, XCC, XBCC, XFOLDER, XORIGIN, XFILENAME,
	//
	BRACES, CLOSEDBRACES
}
