package de.typology.lexerParser;

public enum EnronToken {
	STRING, UPPERCASE, OTHER, WS, LINESEPARATOR, EOF, HEADER,
	//
	FULLSTOP, COMMA, HYPHEN, EXCLAMATIONMARK, QUESTIONMARK, QUOTATIONMARK, AND,

	//
	MESSAGEID, DATE, FROM, TO, CC, BCC, SUBJECT, MIMEVERSION, CONTENTTYPE, CONTENTTRANSFERENCODING, XFROM, XTO, XCC, XBCC, XFOLDER, XORIGIN, XFILENAME,
	//
	BRACES, CLOSEDBRACES
}
