package de.typology.lexerParser;

public enum ReutersToken {
	STRING, UPPERCASE, OTHER, WS, LINESEPARATOR, EOL, EOF,
	//
	FULLSTOP, COMMA, HYPHEN, EXCLAMATIONMARK, QUESTIONMARK, QUOTATIONMARK, AND,

	//
	BRACES, CLOSEDBRACES,
	//
	P, CLOSEDP,
	//
	TITLE, CLOSEDTITLE,
	//
	TEXT, CLOSEDTEXT,
}
