package de.typology.lexerParser;

public enum ReutersToken {
	OBJECT, STRING, OTHER, WS, LINESEPERATOR, URI, EOL, EOF, FULLSTOP, COMMA, HYPHEN, EXCLAMATIONMARK, QUESTIONMARK, QUOTATIONMARK,
	//
	INFOBOX,
	//
	LINK, LABELEDLINK,
	//
	P, CLOSEDP,
	//
	TITLE, CLOSEDTITLE,
	//
	TEXT, CLOSEDTEXT,
	//
	REF, CLOSEDREF
}
