package de.typology.lexerParser;

public enum WikipediaToken {
	OBJECT, STRING, OTHER, WS, LINESEPARATOR, URI, EOF, FULLSTOP, COMMA, SEMICOLON, COLON, EQUALITYSIGN, ASTERISK, HYPHEN, EXCLAMATIONMARK, QUESTIONMARK, QUOTATIONMARK, VERTICALBAR,
	//
	BRACKET, CLOSEDBRACKET, CURLYBRACKET, CLOSEDCURLYBRACKET, SQUAREDBRACKET, CLOSEDSQUAREDBRACKET,
	//
	EHH, CLOSEDEHH, // EHH=<!--<, CLOSEDEHH=!-->
	//
	LINK, LABELEDLINK,
	//
	PAGE, CLOSEDPAGE,
	//
	TITLE, CLOSEDTITLE,
	//
	TEXT, CLOSEDTEXT,
	//
	REF, CLOSEDREF,
	//
	IMAGEMAP, CLOSEDIMAGEMAP
}
