package de.typology.lexerParser;

public enum WikipediaToken {
	OBJECT, STRING, OTHER, WS, LINESEPARATOR, URI, EOF, FULLSTOP, COMMA, COLON, HYPHEN, EXCLAMATIONMARK, QUESTIONMARK, QUOTATIONMARK, VERTICALBAR,
	//
	BRACKET, CLOSEDBRACKET, CURLYBRACKET, CLOSEDCURLYBRACKET, SQUAREDBRACKET, CLOSEDSQUAREDBRACKET,
	//
	INFOBOX,
	//
	LINK, LABELEDLINK,
	//
	PAGE, CLOSEDPAGE,
	//
	TITLE, CLOSEDTITLE,
	//
	TEXT, CLOSEDTEXT,
	//
	REF, CLOSEDREF
}
